export const ADD_EXPENSE = 'ADD_EXPENSE';
export const GET_EXPENSE = "GET_EXPENSE";
export const GET_PROFIT = "GET_PROFIT";
export const CALCULATE_BALANCE = "CALCULATE_BALANCE";
export const GET_LATEST_BALANCE = "GET_LATEST_BALANCE";
export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const DELETE_PROFIT = "DELETE_PROFIT";